routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/CajeroMenu','MenuController@index')->name('MenuCajero');
Route::resource('CajeroMenu','MenuController');
Route::resource('Venta','VentaController');
Route::resource('DetallesVenta','DetallesVentaController');
Route::resource('Taquero','TaqueroController');
Route::resource('Cobrar','CobrarController');
Route::get('/Actualizar/{DetallesVentum}', 'DetallesVentaController@Actualizar')->name('Actualizar');
Route::get('/Comentario/{DetallesVentum}', 'DetallesVentaController@Comentario')->name('Comentario');
Route::get('/Cancelar/{Ventum}', 'VentaController@Cancelar')->name('Cancelar');
Route::get('/Actualizarmenos/{DetallesVentum}', 'DetallesVentaController@Actualizarmenos')->name('Actualizarmenos');
Route::get('/PDF/{Ventum}', 'CobrarController@pdf')->name('PDF');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/Cantidad/{DetallesVentum}', 'DetallesVentaController@Cantidad')->name('Cantidad');

app/Http/Controllers/TaqueroController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Menu;
use App\DetallesVenta;
use App\Venta;


class TaqueroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Ventas = Venta::where('Estatus','En Proceso')->get();
        $Detalle = DB::table('menus')
            ->join('detalles_ventas','detalles_ventas.FkIdPlatillo','=','menus.IdPlatillo')
            ->select('detalles_ventas.FkIdVenta','detalles_ventas.id','detalles_ventas.Cantidad','detalles_ventas.Precio','detalles_ventas.Comentarios','menus.Nombre')->get();

        //dd($Ventas);
        return view('Taquero.index',['Ventas'=>$Ventas,'Detalles'=>$Detalle]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Taquero/index.blade.php
@extends('layouts.app')

@section('content')

    <div style="background: teal;">
        <div class="container"  >
            <nav class="navbar navbar-expand-lg pt-2 mt-0">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <a class="navbar-brand" href="{{route('home')}}" style="color: white">Inicio</a>
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('CajeroMenu.index')}}" style="color: white">Cajero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('Venta.index')}}" style="color: white">Mesero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('Taquero.index')}}" style="color: white">Taquero</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <div class="container-fluid mt-2">
        <div class="row">
            @foreach($Ventas as $venta)
            <div class="col-6 col-lg-3 col-md-4 col-sm-6">


                    <div class="card">
                        <div class="card-header" style="background: darkorange; text-align: center; color: white" >
                            Pedido #{{$venta->id}} para {{$venta->Mesa}}
                        </div>
                        <div class="card-body">
                            <table class="table">
                                        <thead  style="background: darkorange; color: white">
                                        <tr>
                                            <th scope="col">Cantidad</th>
                                            <th scope="col">Producto</th>
                                            <th scope="col">Comentario</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @for($i=0;$i<count($Detalles);$i++)
                                            @if($venta->id == $Detalles[$i]->FkIdVenta)
                                        <tr>
                                            <th> {{$Detalles[$i]->Cantidad}} </th>
                                            <td> {{$Detalles[$i]->Nombre}} </td>
                                            <td> {{$Detalles[$i]->Comentarios}} </td>
                                        </tr>
                                            @endif
                                        @endfor
                                        </tbody>
                                    </table>

                            <a href="{{route('Venta.edit',$venta->id)}}" class="btn btn-primary">Pedido Finalizado</a>
                        </div>
                    </div>


            </div>
            @endforeach
        </div>
    </div>

<!--Modal-->


@endsection